spring:
  datasource:
    url: jdbc:mysql://server.anymre.top:8926/auth-server?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: c1234567
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update