spring:
  datasource:
    url: jdbc:mysql://server.anymre.top:8926/test2?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: c1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8013